# Generated by Django 3.1.4 on 2020-12-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201224_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(default='default', max_length=50, verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
