# Generated by Django 3.1.4 on 2021-01-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210109_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='checkbox_style',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
